# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: docker:latest

stages:
  - build
  - checks

services:
  - docker:dind

build:
  stage: build
  script:
  - docker login registry.gitlab.com -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build --file ./compose/local/django/Dockerfile . -t registry.gitlab.com/{{ cookiecutter.gitlab_username }}/{{ cookiecutter.gitlab_project }}:$CI_COMMIT_SHA
  - docker push registry.gitlab.com/{{ cookiecutter.gitlab_username }}/{{ cookiecutter.gitlab_project }}:$CI_COMMIT_SHA

test:
  stage: checks
  image: registry.gitlab.com/{{ cookiecutter.gitlab_username }}/{{ cookiecutter.gitlab_project }}:$CI_COMMIT_SHA
  services:
    - postgres:{{ cookiecutter.postgresql_version }}
  variables:
    POSTGRES_DB: ci
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_HOST: postgres
  script:
    - py.test --ds=config.settings.test -s -v -x --ff

lint:
  stage: checks
  image: registry.gitlab.com/{{ cookiecutter.gitlab_username }}/{{ cookiecutter.gitlab_project }}:$CI_COMMIT_SHA
  script:
    - flake8
    - black --check
