# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: docker:latest

variables:
  REGISTRY: "registry.gitlab.com"
  GROUP_NAME: "{{ cookiecutter.gitlab_username }}"
  PROJECT_NAME: "{{ cookiecutter.gitlab_project }}"
  CONTAINER_RELEASE_IMAGE: "$REGISTRY/$GROUP_NAME/$PROJECT_NAME:$CI_COMMIT_SHA"

stages:
  - build
  - checks

services:
  - docker:dind

build:
  stage: build
  script:
  - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$REGISTRY"
  - docker build --file ./compose/local/django/Dockerfile . -t $CONTAINER_RELEASE_IMAGE
  - docker push $CONTAINER_RELEASE_IMAGE

test:
  stage: checks
  image: $CONTAINER_RELEASE_IMAGE
  services:
    - postgres:{{ cookiecutter.postgresql_version }}
  variables:
    POSTGRES_DB: ci
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_HOST: postgres
  script:
    - py.test --ds=config.settings.test -s -v -x --ff

lint:
  stage: checks
  image: $CONTAINER_RELEASE_IMAGE
  script:
    - flake8
    - black --check
